### ISSUE TITLE
Many services don't work in MacOS Sequoia

### ISSUE THREAD

**Issue by 63045** [mullvad/mullvadvpn-app#6521]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

When connected to Mullvad on MacOS Sequoia, I cannot send or receive messages on iMessage, even with split tunneling enabled and iMessage excluded.

### Expected Behavior

I expect to be able to send/receive messages.

### Steps to Reproduce

Self-explanatory

### Operating system version

macOS 15.0 Beta

### Mullvad VPN app version

2024.4

### Additional Information

Some other iCloud-related services seem to work. iCloud Drive, Apple Mail, etc.

**Comment by nocturne1** [comment]
Apple news fails as well - all sources are grayed out when tunnel is active.
I also am unable to establish any connection when split tunneling is enabled for any app, so there appears to be an issue there too.

**Comment by drpoutine** [comment]
Has more issues on Sequoia as well. Such as Mullvad not starting up when you login/restart the OS
Lot of macOS issues on 15.0 and 15.1 (similar issues on both)

**Comment by nocturne1** [comment]
The messages app issue continues to exist on 2024.5-beta1 running on the latest macOS 15.0 Beta (24A5331b).
Interestingly enough, the Apple News issue I mentioned above was resolve a few macOS betas ago.

**Comment by 63045** [comment]
FaceTime is broken as well. Incoming calls don't appear and outgoing calls just hang.

**Comment by BionicBison05** [comment]
Any update on this? macOS 15 is due to release in a week, and I'd like to able to upgrade when it does.

**Comment by nocturne1** [comment]
I haven't tried it with today's beta release, but I've found that using the Wireguard app works just fine. So I've been using that for now.

**Comment by raksooo** [comment]
Hi, thanks for reporting this issue. We are aware of it and will look into it soon.

**Comment by Irv72** [comment]
Still not working in the Release Candidate, so don't upgrade unless something changes.

I submitted the bug to Mullvad more than a month ago, through the VPN app, and received an acknowledgement. So they've known about it for a while. Hopefully, a fix is coming, because it's very annoying.

**Comment by m-c-program** [comment]
Beating a dead horse since I'm pretty sure it's exactly the same networking wise as 15.0 RC, but 15.1 build 24B5035e also has the same issues.

**Comment by Serock3** [comment]
Hello. I am chiming in to say that this is a high priority issue and that we are actively investigating possible solutions. We have no time-frame for a fix yet, unfortunately, but we are taking it seriously.

**Comment by drpoutine** [comment]
Same issue reported in https://github.com/mullvad/mullvadvpn-app/issues/6555

**Comment by JohnMiltonSr** [comment]
macos 15 sequoia, apple silicon, using latest version of mullvad.

messages app is the only one that seems affected. i cannot send or receive messages. news, mail, and weather apps all unaffected for me.

the only way to get the messages app to update with new messages is to manually sync through icloud settings (not in messages app). only then do the messages from iphone load into the mac messages app. however, if i try to do the same thing via the messages app (messages app also has an option to manually sync with icloud), it doesn't work.

**Comment by faridchaouki** [comment]
Same issue here with the official release of MacOS Sequoia 15.0.
Split Tunneling is Off and problem persists with Messages not being able to send or receive.

**Comment by bwrightkc** [comment]
Issue also exists in 15.1 Beta build 24B5046f. Not resolved by disabling quantum tunneling either.

**Comment by user733626** [comment]
Same problem here! I had to uninstall the official mullvad app and install wireguard which seems to be working fine with all icloud services such as messages etc...
Any progress on the bug @raksooo ?

**Comment by user733626** [comment]
> > Same problem here! I had to uninstall the official mullvad app and install wireguard which seems to be working fine with all icloud services such as messages etc... Any progress on the bug @raksooo ?
> 
> 
> 
> Wait so u can download the official Wireguard App and use your mullvad account through it ?

yep you can, you just have to download the file with all the servers while logged-in to your account in browser + you can even choose which DNS content blockers you wanna use as well before downloading the file

**Comment by JohnMiltonSr** [comment]
wanted to add that the only significant change to messages in macos 15 is the addition of the RCS protocol (for android/non-iphone texting). because no other mac apps seem to be affected, maybe this is connected to the bug? @Serock3

**Comment by MarkusPettersson98** [comment]
@ccconcrete Yes, you can [use the vanilla Wireguard App with Mullvad](https://mullvad.net/en/help/wireguard-macos-app) :blush:

**Comment by mdl054** [comment]
Experiencing the same issues here, Messaging is the obvious piece, however I'm now unable to turn off Lockdown Mode. Disabling does nothing, internet still blocked while disconnected. Kind of a big deal as obviously some sites will no longer work while connected to Mullvad and now you no longer have the option of disconnecting. Hopefully this gets a priority.

**Comment by JohnMiltonSr** [comment]
> > > Same problem here! I had to uninstall the official mullvad app and install wireguard which seems to be working fine with all icloud services such as messages etc... Any progress on the bug @raksooo ?
> > 
> > 
> > Wait so u can download the official Wireguard App and use your mullvad account through it ?
> 
> yep you can, you just have to download the file with all the servers while logged-in to your account in browser + you can even choose which DNS content blockers you wanna use as well before downloading the file

do you know if split tunneling on a per app basis is possible using the official wireguard app or a fork? i had mullvad split tunnel enabled for firefox so i could use no proxy for certain websites that don't like mullvad vpn and it would be nice to get this feature back while we wait for a fix

**Comment by banister** [comment]
> Same problem here! I had to uninstall the official mullvad app and install wireguard which seems to be working fine with all icloud services such as messages etc... Any progress on the bug @raksooo ?

@user733626 are you sure the WireGuard app has a firewall? the issue seems to be that Apple forcibly bind iMessage to the physical interface so the killswitch will block its traffic. Obviously if you don't have a killswitch (which blocks off-VPN traffic) then iMessage will work, but it's also leaking like crazy out the physical, so not a good solution.

**Comment by user733626** [comment]
> > Same problem here! I had to uninstall the official mullvad app and install wireguard which seems to be working fine with all icloud services such as messages etc... Any progress on the bug @raksooo ?
> 
> 
> 
> @user733626 are you sure the WireGuard app has a firewall? the issue seems to be that Apple forcibly bind iMessage to the physical interface so the killswitch will block its traffic. Obviously if you don't have a killswitch (which blocks off-VPN traffic) then iMessage will work, but it's also leaking like crazy out the physical, so not a good solution.

really? Didn't know, thanks. I guess we have to wait for the fix from Mullvad team then.

**Comment by banister** [comment]
@user733626 tbh, i think the fix should come from Apple - it impacts all VPN apps and VPN-like apps, like little snitch too iirc.

**Comment by lvalen91** [comment]
Either Mullvad needs to re-enable the option to disable kill-switch or use the macOS VPN service like wireguard does. Sure, Apple should work with Mullvad and the others to fix this issue.

I don't know the specifics, but macOS kernel log just shows a repeating iCloud/iMessage server handshake and token attempts. If this is part of Apple increasing security then Mullvad and the others would have to fix it. If it's an unintended macOS Sequoia bug, then it's on Apple.

My limited understanding of App based VPN services is that the APP "hijacks" the network stack / routing table. Routing traffic through its internal VPN tunnel *magic*. On iPadOS and iOS, Mullvad uses the built-in VPN service/proccess. So that would explain why most users, me included, have not seen issues on those devices using a VPN app. Since the wireguard app goes through the macOS VPN service. It would also explain or at lease shine some light on why certain apps or configs work and others don't.

For now having wireguard inject the Mullvad servers into the macOS VPN manager seems to work just fine. It also seems cleaner maybe more secure? idk

**Comment by octypus** [comment]
> @user733626 tbh, i think the fix should come from Apple - it impacts all VPN apps and VPN-like apps, like little snitch too iirc.

Most other VPN apps were updated to use MacOS VPN services months ago. When I updated to Sequoia and realized that Mullvad was broken I tested Proton, Surfshark, and Nord. All three were already using macOS VPN services and work just fine. This isn't Apple's fault. It was well known that these changes were coming with MacOS 15 as these new services existed in all the beta builds. Some apps (like Mullvad and Little Snitch) just never got around to updating their apps and now they're broken.

**Comment by kp-john-mair** [comment]
Last time I checked, Nord was leaky like crazy on macOS. That's probably why it works, they don't have a proper Killswitch. I bet the same is true with proton and surfshark famously has one of the worst killswitches in the business.

I don't believe it's a "good thing" those apps work. it just indicates they leak. The reason mullvad doesn't leak apple traffic is because it has a functioning Killswitch.

**Comment by banister** [comment]
Last time I checked, Nord was leaky like crazy on macOS. That's probably why it works, they don't have a proper Killswitch. I bet the same is true with proton and surfshark famously has one of the worst killswitches in the business.

I don't believe it's a "good thing" those apps work. it just indicates they leak. The reason mullvad doesn't allow apple traffic on the physical interface is because it has a functioning Killswitch.

Yep, just like i thought, proton vpn - with killswitch TURNED on leaks like crazy to apple servers. Setup `tcpdump` and listen on the `17.0.0.0/8` range - it's leaking everything to apple over the physical interface. Looks like your wonderful "Apple VPN APIs" whitelist apple ips. Great. But using lower-level APIs like mullvad does, they don't play apple's game, and get to decide exactly which traffic gets through on the physical - whether it's Apple traffic or not.

**Comment by perara-chen** [comment]
I just upgraded my macOS to sequoia (stable) yesterday and mullvad vpn stopped working since then. VPN connection to the desired server could be established but all of the internet related services stop working. It is like using a WiFi connection which does not have the internet access. It seems to be WiredGuard related problem. Switching protocol to OpenVPN has no problems so far.

**Comment by banister** [comment]
@raksooo How's the research going? i found a fix for this, LMK if you'd like to discuss it

**Comment by Tech6767** [comment]
Hey, in case most of you haven't noticed so far: https://github.com/objective-see/LuLu/issues/637#issuecomment-2356910348

The easiest workaround seems to be to disable the MacOS Firewall.

**Comment by bwrightkc** [comment]
> Hey, in case most of you haven't noticed so far: [objective-see/LuLu#637 (comment)](https://github.com/objective-see/LuLu/issues/637#issuecomment-2356910348)
> 
> The easiest workaround seems to be to disable the MacOS Firewall.

Hm. I've always had the MacOS firewall off (and verified that it is off now) and it is still having the same issues with iMessages and other apple services being unable to connect.

**Comment by kp-john-mair** [comment]
@Tech6767 it's unrelated to that, it's all to do with how the `apsd` process now behaves when the VPN comes up.

**Comment by banister** [comment]
@Tech6767  it's unrelated to that, it's all to do with how the `apsd` process now behaves when the VPN comes up.

**Comment by qwertyasdfasdfqwerty** [comment]
Issue persists even with the new beta and Apple services bypass enabled. 

Messages do not come through at all. As soon as I disconnect the Mullvad app and restart the Wireguard app using a Mullvad profile, the Messages eventually populate and sync.

**Comment by JohnMiltonSr** [comment]
> Issue persists even with the new beta and Apple services bypass enabled.
> 
> Messages do not come through at all. As soon as I disconnect the Mullvad app and restart the Wireguard app using a Mullvad profile, the Messages eventually populate and sync.

same. new beta does nothing for me

**Comment by longlantom** [comment]
The new beta worked for me!

**Comment by qwertyasdfasdfqwerty** [comment]
> The new beta worked for me!

Can you confirm what version of MacOS 15 including the build number you're using, as well as an example of a server and the settings that seem to be working as expected for you?

**Comment by longlantom** [comment]
> Can you confirm what version of MacOS 15 including the build number you're using, as well as an example of a server and the settings that seem to be working as expected for you?
>
I'm currently on Sequoia (24A335), connecting to Singapore server with Apple services bypass toggle turned on, and iMessage just work like a champ.

**Comment by qwertyasdfasdfqwerty** [comment]
> > Can you confirm what version of MacOS 15 including the build number you're using, as well as an example of a server and the settings that seem to be working as expected for you?
> 
> I'm currently on Sequoia (24A335), connecting to Singapore server with Apple services bypass toggle turned on, and iMessage just work like a champ.

Thanks. I'm actually on 15.1 Beta (24B5055e). Not sure if that might make a difference. 

I'll test further tomorrow assuming things don't magically start working as expected overnight.

**Comment by longlantom** [comment]
> > I'm currently on Sequoia (24A335), connecting to Singapore server with Apple services bypass toggle turned on, and iMessage just work like a champ.
> 
> Thanks. I'm actually on 15.1 Beta (24B5055e). Not sure if that might make a difference.
> 
> I'll test further tomorrow assuming things don't magically start working as expected overnight.

Btw, I forgot mentioned that I've also add iMessage to Split tunnel, you could try that if you didn't
<img width="322" alt="image" src="https://github.com/user-attachments/assets/5cab311f-04b6-4dfc-b45c-2fe3beca1ca5">

**Comment by nocturne1** [comment]
I can confirm, [2024.6-beta1](https://github.com/mullvad/mullvadvpn-app/releases/tag/2024.6-beta1) Mullvad client works for me, with Apple Service Bypass enabled.

**Comment by qwertyasdfasdfqwerty** [comment]
> I can confirm, [2024.6-beta1](https://github.com/mullvad/mullvadvpn-app/releases/tag/2024.6-beta1) Mullvad client works for me, with Apple Service Bypass enabled.
> 
> Update - maybe I spoke too soon. My first test message went through, but a few hours late, nothing is showing up between them.

Yeah, there is some kind of inconsistency going on. 

Upon a full restart, it doesn't work at all. Messages come through on my iphone and I get nothing on the mac. Again, if I disconnect the Mullvad app, start the Wireguard app, everything works. What I've then noticed is that if I disconnect the Wireguard app and turn the Mullvad app back on and connect, things continue to seem to work for a while. That could mean it's working, or it could mean that something is leaking.

I've fallen back to just using the Wireguard app in the meantime, something isn't quite right still.

**Comment by user733626** [comment]
I think that iCloud services are having some global issues as well. My iMessage gets logged off on both my iPhone and mac for no reason since yesterday or I'm not getting notifications from multiple apps on my phone but getting them on macOS. Apple should get their stuff together TBH...

**Comment by banister** [comment]
PIA Released a fix for this too: https://www.reddit.com/r/PrivateInternetAccess/comments/1fqt46d/restoring_apple_app_connectivity_on_macos_15/ 

Also includes technical details of the problem and the fix.

**Comment by joeywreck** [comment]
The beta didn't make a difference at all. It's starting to hit me that I haven't been able to use the official Mullvad app since July. I really hope this is fixed shortly.

**Comment by jordanful** [comment]
Kinda....want my bitcoin back.

**Comment by joeywreck** [comment]
> Kinda....want my bitcoin back.

I wouldn’t go that far in my case because I can still connect to Mullvad servers using WireGuard, and I mainly pay for the VPN service itself, not the kill switches, multi-hop, or other features. I just miss the extra features and not having to do things manually lol

**Comment by bedesv** [comment]
I can confirm that I'm still having this issue on Mullvad 2024.6-beta1 and macOS Version 15.1 Beta (24B5009l)

**Comment by yasoobkhalid1** [comment]
> Last time I checked, Nord was leaky like crazy on macOS. That's probably why it works, they don't have a proper Killswitch. I bet the same is true with proton - and surfshark famously has one of the worst killswitches in the business.
> 
> I don't believe it's a "good thing" those apps work. it just indicates they leak. The reason mullvad doesn't allow apple traffic on the physical interface is because it has a functioning Killswitch.
> 
> Yep (just tested), just like i thought, proton vpn - with killswitch TURNED ON leaks like crazy to apple servers. Setup `tcpdump` and listen on the `17.0.0.0/8` range - it's leaking everything to apple over the physical interface. Looks like your wonderful "Apple VPN APIs" whitelist apple ips. Great. But using lower-level APIs like mullvad does, they don't play apple's game, and get to decide exactly which traffic gets through on the physical - whether it's Apple traffic or not.

Can confirm that Wireguard works but looking at `tcpdump` for `17.0.0.0/8`, it is _definitely_ leaking quite a bit. So even if Wireguard is a workaround, not sure how useful it is if the VPN fails in its main purpose.

Hopefully the online community can figure out how to bypass this `apsd` issue - kinda insane that it's affecting so many services that there are multiple articles about it online, yet Apple hasn't hotfixed it yet.

**Comment by kp-john-mair** [comment]
> 
> Can confirm that Wireguard works but looking at `tcpdump` for `17.0.0.0/8`, it is _definitely_ leaking quite a bit. So even if Wireguard is a workaround, not sure how useful it is if the VPN fails in its main purpose.

@yasoobkhalid1 i believe the temporary fix for this (until apple fixes the bug) is to allow 17/8 out the physical. But at least it should be deliberate, rather than a built-in unavoidable leak like the WireGuard leak.

**Comment by jrabinow** [comment]
I can regularly repro when waking my mac up from sleep - not systematically, but very (more than ~75% of the time) often. The mac wakes up from sleep and there's no internet connectivity, even though I am still on wifi and can talk to everything on my LAN.
Mullvad app just spins and shows "attempting to connect" without even mentioning a specific server. I've been able to make things go back to normal by rebooting the laptop.

As a workaround, I've taken to 1/ disabling mullvad and 2/ turning off wifi before putting the machine to sleep. I'm not sure 2/ actually helps but since doing this, I can wake up the mac, connect to wifi, turn the VPN on and everything works like a charm.

Today I forgot to turn off wifi before going to sleep, and ran into the same issue. I started poking around a bit, and long story short:
- I'm convinced this is a default route issue, I'm afraid I lost the output from my `netstat -ne` but I can share it next time this happens if that'd be of help.
- I noticed that `mullvad-daemon` process was still running despite the fact I had quit the mullvad app. I tried poking it a little and eventually just killed (or `kill -9`?)'ed it. It restarted right away with a different PID - and internet started working again, no reboot.

Hopefully the above helps pin down the problem

**Comment by qwertyasdfasdfqwerty** [comment]
> > Can confirm that Wireguard works but looking at `tcpdump` for `17.0.0.0/8`, it is _definitely_ leaking quite a bit. So even if Wireguard is a workaround, not sure how useful it is if the VPN fails in its main purpose.
> 
> @yasoobkhalid1 i believe the temporary fix for this (until apple fixes the bug) is to allow `17/8` out the physical. But at least it should be deliberate, rather than a built-in unavoidable leak like the WireGuard leak.

Do we know for certain that this is indeed a bug on the Apple side of things, and not just a change they've made in how network traffic for Apple services will work going forward?

**Comment by banister** [comment]
@qwertyasdfasdfqwerty Good question, i'm not 100% sure tbh. It's unfortunate if they choose this approach though, as this means Apple traffic will always leak out the physical.

**Comment by qwertyasdfasdfqwerty** [comment]
> @qwertyasdfasdfqwerty Good question, i'm not 100% sure tbh. It's unfortunate if they choose this approach though, as this means Apple traffic will always leak out the physical.

Yeah, that's my been my concern as I've seen how this has played out across various apps that have been impacted. Not sure why they would make a change like that that negatively impacts so many different pieces of software. Hopefully we can get some clarification on this somehow, or perhaps the behavior will be different whenever the next beta updates are released. 

Hopefully enough people have actually submitted proper bug reports through the Apple feedback app as well. (Highly suggested folks do this if they have not already!)

**Comment by yasoobkhalid1** [comment]
Is there any update from the Mullvad team regarding an ETA for an anticipated fix? It's been a few weeks since the last update, so I'm curious if there's been any progress? It's pretty frustrating to use a VPN without its primary purpose: to hide your traffic.

**Comment by ImTheSquid** [comment]
According to Feedback Assistant it seems that Apple is aware of the issue and is working on a fix.
<img width="423" alt="image" src="https://github.com/user-attachments/assets/059caf42-5f7b-4cb2-a038-5770ff3e2d77">

**Comment by luckman212** [comment]
Great. Let's just hope that fix lands in 15.1 and not 15.2.

**Comment by hulthe** [comment]
> Is there any update from the Mullvad team?

I can give you a small one.

We're not satisfied with the Apple Services Bypass "fix" that we rushed out in the latest beta, it's obviously not very reliable. We have a potential real fix in the pipeline, and so far it's looking promising. Can't give you an ETA yet though.

We're happy that Apple seem to be working on a fix, but we're not sitting around waiting for them.

We'll make sure to post any further updates here when we have them.

**Comment by ioanmdev** [comment]
After installing Mullvad 2024.6-beta1 and enabling Apple Services Bypass, iMessage and Facetime work (albeit by bypassing the tunnel). I've yet to encounter any issue using them on macOS 15.0 (the stable version)

**Comment by ioanmdev** [comment]
> @ioanmdev cool. Can you send images over iMessages too?

Yes, it works flawlessly.

**Comment by yasoobkhalid1** [comment]
> After installing Mullvad 2024.6-beta1 and enabling Apple Services Bypass, iMessage and Facetime work (albeit by bypassing the tunnel). I've yet to encounter any issue using them on macOS 15.0 (the stable version). I've been using it for the past few days and so far it's been a good experience. There may be some reliability issues with macOS 15.1 beta, as others have pointed out.

Just tried replicating this - also using 2024.6-beta1 with Apple Services Bypass enabled, running on macOS 15.0.

Unfortunately, this didn't work for me - iMessage still fails to send any texts :(

**Comment by ioanmdev** [comment]
> > After installing Mullvad 2024.6-beta1 and enabling Apple Services Bypass, iMessage and Facetime work (albeit by bypassing the tunnel). I've yet to encounter any issue using them on macOS 15.0 (the stable version). I've been using it for the past few days and so far it's been a good experience. There may be some reliability issues with macOS 15.1 beta, as others have pointed out.
> 
> Just tried replicating this - also using 2024.6-beta1 with Apple Services Bypass enabled, running on macOS 15.0.
> 
> Unfortunately, this didn't work for me - iMessage still fails to send any texts :(

So far, i tried sending SMS, sending MMS, sending iMessage to myself, sending iMessage to a friend and the same with image. All while being connected over Wireguard protocol, no obfuscation, Local network sharing enabled, IPv6 enabled, Quantum Resistant On, no DAITA, no Multihop.

**Comment by ioanmdev** [comment]
![Screenshot 2024-10-02 at 22 56 17](https://github.com/user-attachments/assets/c8788ccb-a510-4245-8d87-6ce192de96d6)

**Comment by yasoobkhalid1** [comment]
> > > After installing Mullvad 2024.6-beta1 and enabling Apple Services Bypass, iMessage and Facetime work (albeit by bypassing the tunnel). I've yet to encounter any issue using them on macOS 15.0 (the stable version). I've been using it for the past few days and so far it's been a good experience. There may be some reliability issues with macOS 15.1 beta, as others have pointed out.
> > 
> > 
> > Just tried replicating this - also using 2024.6-beta1 with Apple Services Bypass enabled, running on macOS 15.0.
> > Unfortunately, this didn't work for me - iMessage still fails to send any texts :(
> 
> So far, i tried sending SMS, sending MMS, sending iMessage to myself, sending iMessage to a friend and the same with image. All while being connected over Wireguard protocol, no obfuscation, Local network sharing enabled, IPv6 enabled, Quantum Resistant On, no DAITA, no Multihop.

Yeah it's so bizarre. My settings are the exact same as yours but iMessage doesn't work at all for me :( the messages keep failing when trying to send them.

<img width="693" alt="image" src="https://github.com/user-attachments/assets/12fe140b-d288-42ee-a3c3-a94d5a961178">

**Comment by ioanmdev** [comment]
> > > > After installing Mullvad 2024.6-beta1 and enabling Apple Services Bypass, iMessage and Facetime work (albeit by bypassing the tunnel). I've yet to encounter any issue using them on macOS 15.0 (the stable version). I've been using it for the past few days and so far it's been a good experience. There may be some reliability issues with macOS 15.1 beta, as others have pointed out.
> > > 
> > > 
> > > Just tried replicating this - also using 2024.6-beta1 with Apple Services Bypass enabled, running on macOS 15.0.
> > > Unfortunately, this didn't work for me - iMessage still fails to send any texts :(
> > 
> > 
> > So far, i tried sending SMS, sending MMS, sending iMessage to myself, sending iMessage to a friend and the same with image. All while being connected over Wireguard protocol, no obfuscation, Local network sharing enabled, IPv6 enabled, Quantum Resistant On, no DAITA, no Multihop.
> 
> Yeah it's so bizarre. My settings are the exact same as yours but iMessage doesn't work at all for me :( the messages keep failing when trying to send them.
> 
> <img alt="image" width="693" src="https://private-user-images.githubusercontent.com/44797724/373016346-12fe140b-d288-42ee-a3c3-a94d5a961178.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5Mjg0MjAsIm5iZiI6MTcyNzkyODEyMCwicGF0aCI6Ii80NDc5NzcyNC8zNzMwMTYzNDYtMTJmZTE0MGItZDI4OC00MmVlLWEzYzMtYTk0ZDVhOTYxMTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA0MDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYWNkYmU1OWRmYTdiNDhjNTAwNjFkODdlMDI3YWQzYzEwYmNmY2M0NjVmZmM5YWNiODdkNDRmNGYyYjAwNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Jy0UNF_Dp2zB_1Fz-IeBJdwk6tmEZZL3a_kGE5rDgII">

Have you tried rebooting macOS?

**Comment by longlantom** [comment]
> Can anyone confirm whether the recently-released 15.0.1 update that "Improves compatibility with third-party security software" fixes this issue?

Recently updated my MacOS to 15.0.1 and it’s still doesn’t work :(

**Comment by ccconcrete** [comment]
MacOS 15.0.1
MullvadVPN 6 beta1
Apple Services Bypass: ON

AirDrop, iMessage, Facetime working with this combo as of now, will report if it stops after a while.

**Comment by parthjaggi** [comment]
> MacOS 15.0.1 
> MullvadVPN 6 beta1
> Apple Services Bypass: ON
> AirDrop, iMessage, Facetime working with this combo as of now, will report if it stops after a while.

Same setup. iMessage doesn't work for me.

**Comment by ioanmdev** [comment]
> > MacOS 15.0.1
> > MullvadVPN 6 beta1
> > Apple Services Bypass: ON
> > AirDrop, iMessage, Facetime working with this combo as of now, will report if it stops after a while.
> 
> Same setup. iMessage doesn't work for me.

Now after 15.0.1 Apple Services Bypass has stopped working for me too.

**Comment by ccconcrete** [comment]
> MacOS 15.0.1 MullvadVPN 6 beta1 Apple Services Bypass: ON
> 
> AirDrop, iMessage, Facetime working with this combo as of now, will report if it stops after a while.

Update: very shaky, kind of works, kind of doesnt sometimes, definitely not fully resolved.

**Comment by qwertyasdfasdfqwerty** [comment]
> > MacOS 15.0.1 MullvadVPN 6 beta1 Apple Services Bypass: ON
> > AirDrop, iMessage, Facetime working with this combo as of now, will report if it stops after a while.
> 
> Update: very shaky, kind of works, kind of doesnt sometimes, definitely not fully resolved.

Basically sums it up. It's inconsistent to the point of straight up being broken, and honestly is a liability to use. 

I'm not sure what the ETA is on the other potential fix that was mentioned a couple days ago, but I'd maybe even go so far as to say that I kind of think this update should be pulled/rolled back. Using the official Wireguard app is the only real "solution" as things currently stand.

**Comment by ldexterldesign** [comment]
👋

Sorry if I've missed it here, if a Mullvad (MV) version exists where this issue doesn't then please let me/us know so I/we can rollback?:
- If yes then MV please enhance your testing before releases
- If no then will assume blame is fully on Apple (i.e. Sequoia will break any version of MV)

Hope to hear back and good luck with fix

🤞

**Comment by raksooo** [comment]
> I'm not sure what the ETA is on the other potential fix that was mentioned a couple days ago, but I'd maybe even go so far as to say that I kind of think this update should be pulled/rolled back.

The current plan is to release a new beta this week (2024.6-beta2) which will include a real fix and it won't contain the current bypass toggle. That will hopefully become a stable release in a couple of weeks.

**Comment by qwertyasdfasdfqwerty** [comment]
A new MacOS 15.1 beta (Beta 6) was just released. Will be testing it shortly.

**Comment by qwertyasdfasdfqwerty** [comment]
Upon initial testing, I think this MAYBE is resolved at least with the latest MacOS beta 15.1 (24B5070a).

I used the Mullvad app as per usual, actually turned OFF Apple Services Bypass, had a text message sent to me, and it immediately came through on the Mac. Hesitant to fiddle with too many other settings in the meantime, but that's what I got. 

Anyone else have any lucky or any other noticeable issues with the latest beta?

**Comment by drpoutine** [comment]
https://developer.apple.com/documentation/macos-release-notes/macos-15_1-release-notes#Messages

I can confirm that it is indeed fixed. all the weird handoff issues and other icloud services related bugs have been resolved as of `macOS 15.1 beta 6 build 24B5070a` on `Mac15,6` . running smoothly using Mullvad for Mac v2024.5. 

using wireguard only with multihop and so far everything seems to be functioning OS-wide. No split app configuration was required. just the local network access for bonjour (its turned off when not at home)
![Screenshot 2024-10-08 at 12 42 54](https://github.com/user-attachments/assets/d6e54b00-71ca-4e9c-a9b4-372cc1c18bef)

imessage and facetime calls all functioning as expected.

**Comment by jordanful** [comment]
The new MacOS beta allows iMessage and FaceTime, but does not work with Continuity Camera / Mic (i.e. I am unable to use my phone as a camera/mic when Mullvad is turned on). Previously this worked.

**Comment by ianclarksmith** [comment]
I tether to my phone often and noticed after the update that, at least with my current combination of iOS 18.0 (22A3354) and macOS 15.0.1, I am only able to use the web with the VPN/Mullvad enabled. Lockdown mode is disabled. Split tunneling is off. Both devices have been restarted numerous times during testing.

This leaves me in a funny position where I can use Apple services only while using a regular wifi network with Mullvad switched off. On the go, I can not use Apple services at all and Mullvad is the only thing which makes my other connections work.

Are there any logs or things I should observe to see if the Mullvad app is somehow involved, lockdown setting being enabled and persisting without showing in the UI or something like that? I can open a separate issue if desired but given the nature of the issue I'm mentioning it here on the theme of "macOS Sequoia things not as expected while using Mullvad".

**Comment by bwrightkc** [comment]
> I tether to my phone often and noticed after the update that, at least with my current combination of iOS 18.0 (22A3354) and macOS 15.0.1, I am only able to use the web with the VPN/Mullvad enabled. Lockdown mode is disabled. Split tunneling is off. Both devices have been restarted numerous times during testing.
> 
> This leaves me in a funny position where I can use Apple services only while using a regular wifi network with Mullvad switched off. On the go, I can not use Apple services at all and Mullvad is the only thing which makes my other connections work.
> 
> Are there any logs or things I should observe to see if the Mullvad app is somehow involved, lockdown setting being enabled and persisting without showing in the UI or something like that? I can open a separate issue if desired but given the nature of the issue I'm mentioning it here on the theme of "macOS Sequoia things not as expected while using Mullvad".

Had this issue in 15.0.1 as well, no longer happening in 15.1 beta 6.

**Comment by drpoutine** [comment]
> The new MacOS beta allows iMessage and FaceTime, but does not work with Continuity Camera / Mic (i.e. I am unable to use my phone as a camera/mic when Mullvad is turned on). Previously this worked.

its entirely possible this is a bug within macOS itself. I've noticed restarting the network daemon til it works seems to be the move

**Comment by raksooo** [comment]
We've now released 2024.6-beta2. It has a fix that forces Apple apps/services traffic to go inside the tunnel instead of being blocked due to trying to go outside the tunnel. Please try it out and let us know how well it works!

**Comment by longlantom** [comment]
The 2024.6-beta2 didn't work for me!

**Comment by ccconcrete** [comment]
> We've now released 2024.6-beta2. It has a fix that forces Apple apps/services traffic to go inside the tunnel instead of being blocked due to trying to go outside the tunnel. Please try it out and let us know how well it works!

My Reply as of now, is that it works, but imessage seems to have a significant delay. ie: It feels like its trying and failing to go through and is stuck for a few seconds attempting to send and then it goes through. So it's working but doesn't seem optimal/fast.

**Comment by davidkamayor** [comment]
I'm on 2024.6-beta2 and I can report that iMessage does work on my Mac, but iPhone mirroring does not.

**Comment by drpoutine** [comment]
> We've now released 2024.6-beta2. It has a fix that forces Apple apps/services traffic to go inside the tunnel instead of being blocked due to trying to go outside the tunnel. Please try it out and let us know how well it works!

not noticing much of a difference between `Mullvad v2024.5` and `v2024.6-beta2` on `macOS 15.1 beta 6 build 24B5070a` with `Mac15,6`

Fixes on the networking stack are still in progress by Apple on 15.1 betas but if i'm not mistaken these fixes are not available to the public yet on `macOS 15.0.1` according to the changelogs and probably won't be until 15.1 is public

macOS 15.0.1 changelog
```
This update provides important bug fixes for your Mac including:
● Messages may unexpectedly quit when replying to a message with a shared Apple Watch face.
● Improves compatibility with third-party security software.
```
The fix is coming soon™ per post [here](https://github.com/mullvad/mullvadvpn-app/issues/6521#issuecomment-2400470346)

iCloud services started to work as soon as `15.1 beta 6` was installed on `v2024.5` 

For those who are asking about iPhone Mirroring not working while connected to mullvad, this requires local network access as it relies on Continuity to function. [Please be informed that there is currently a privacy bug when using iPhone Mirroring](https://www.sevcosecurity.com/iphone-mirroring-expose-employee-personal-information/)

*also yes its weird it doesnt work when the iphone is wired into your mac 0-0*

**Comment by yasoobkhalid1** [comment]
Can also confirm that iMessage is finally working on the `v2024.6-beta2`! And as `drpoutine` mentioned above, iPhone Mirroring also works once local network access is turned on in Mullvad.

Unfortunately, when I set up `tcpdump` and listened to `17.0.0.0/8`, traffic still seemed to be leaking to Apple over the physical interface (like we discovered earlier in this thread) 😞 

Am I doing something wrong? Want to make sure we avoid being similar to some of the other VPNs (like Proton) where iMessage was working, but that was just because they were leaking all their traffic to Apple. 

@banister would you able to check and see if the new version still leaks on your end?

**Comment by buggmagnet** [comment]
Hi @yasoobkhalid1 
Can you tell us what's your setup for running `tcpdump` ? 
Here's the setup I used to confirm that we're not leaking traffic. 
- Run `v2024.6-beta2` on macOS Sequoia 15.0.1
- Turn on Mullvad
- Connect to a router I control, and that is connected to internet
- On the router, I run `tcpdump` which I then [pipe into Wireshark](https://wiki.wireshark.org/CaptureSetup/Pipes). You can do this without Wireshark, but it makes for a nicer UX
- In wireshark, I then use the filter `not wg` to filter out all the WireGuard traffic, since I want to see what goes outside of the tunnel
- I start sending messages via iMessage from my mac computer to another iPhone that is only using 4G to make sure I'm not on the same network as the mac computer.

With this setup, I can see that Apple's iMessage traffic is not leaking outside of the tunnel.

For good measure, I was also running Wireshark on the mac computer itself, and using the same filter (`not wg`) I could not see traffic leaving the tunnel.

Can you share your setup, and repro steps as well ? 
Did you mean to say that iPhone mirroring is leaking traffic to Apple ?

**Comment by kp-john-mair** [comment]
You're filtering on every interface, but it's only a leak if your 17/8 packets are appearing on the physical interface (typically en0 or en1)

**Comment by Malachai7** [comment]
I think I figured out the issue now.... 

For Mac users what I did was log out of Mullvah , quit the program then uninstalled it from my machine. Once that was done I restarted the macbook . Went  to the Mullvah site and downloaded the software .Once that was done I entered my info then log in. Once that was done I did my test and iMessage started working without any issue. 

Hopefully that helps because I was pissed today when I upgraded my mac.

**Comment by synfinner** [comment]
After doing an uninstall and reinstall of the 2024.6-beta2 (didn't matter how I changed settings), I kept getting 0 networking activity on (15.0.1 (24A348)). Switching back to release 2024.5 and can connect to services normally. Will try and get a packet dump later.

**Comment by magidandrew** [comment]
Can confirm that the 2024.6-beta2 WORKS on macos 15.1 with the apple services bypass 🎉

**Comment by yasoobkhalid1** [comment]
> Can confirm that the 2024.6-beta2 WORKS on macos 15.0.1 with the apple services bypass 🎉

I believe the 2024.6-beta2 version removes the bypass? I think they intend for the VPN to work on that version without it.

**Comment by MarkusPettersson98** [comment]
>> Can confirm that the 2024.6-beta2 WORKS on macos 15.0.1 with the apple services bypass 🎉

> I believe the 2024.6-beta2 version removes the bypass? I think they intend for the VPN to work on that version without it.

It is true that we removed the bypass in 2024.6-beta2, and it will not be included in the upcoming stable release.

**Comment by jhariani** [comment]
Just an FYI that the [macOS Sequoia 15.1 RC Release Notes](https://developer.apple.com/documentation/macos-release-notes/macos-15_1-release-notes) has this note:

[Messages](https://developer.apple.com/documentation/macos-release-notes/macos-15_1-release-notes#Messages)
[Resolved Issues](https://developer.apple.com/documentation/macos-release-notes/macos-15_1-release-notes#Resolved-Issues)
Fixed an issue preventing iMessage and other third-party notifications from being received while your device is connected on a VPN. (136775545)

**Comment by kminevskiy** [comment]
After updating to 15.1 today, I can confirm that iMessage works with the non-beta Mullvad desktop app.

**Comment by DefiDebauchery** [comment]
So what's the status of this? Does Mullvad 2024.7 and macOS 15.1 _fully_ correct leakage without any bypasses or other compromises?

**Comment by raksooo** [comment]
# Apple services
Apple services are working since 2024.6. Neither 2024.6 nor 2024.7 contains the bypass solution and therefore don't solve this by leaking. Traffic was never leaking unless you enabled the bypass that was available in 2024.6-beta1 (and then removed in beta2).

This issue has has also been fixed on Apples end in macOS 15.1 which therefore works with earlier versions of our app.

# Leaks after upgrade
We've had a separate issue about leaks after upgrading macOS, see [our blog about this](https://mullvad.net/en/blog/macos-sometimes-leaks-traffic-after-system-updates). We've had a difficult time reproducing this and currently don't have any news. Our current recommendation is to test wether or not you are leaking after a system upgrade and reboot if you are.

We are aiming to provide an update when we know more.

## Moving forward
We are currently experimenting with making the app actively check for leaks to notify users.
